spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: DECG
    filters: stat, wall, log4j
  druid:
    initial-size: 1
    max-active: 100


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0 #默认是索引为的0的数据库